name: Conditions steps
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.job_outcome.outputs.outcome }}
    steps:
      - name: print greeting
        run: |
          echo "First job"
          exit 1
      - name: print good bye
        id: job_outcome
        run: |
          echo "Byee"
          echo "Multi Line Shell Commands"
          echo "outcome='failure'" >> $GITHUB_OUTPUT
  second-job:
    needs: ['first-job']
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: print greeting
        run: echo "Second job"
      - name: print good bye
        run: |
          echo "Byee"
          echo "Multi Line Shell ${{ needs.first-job.outputs.result }}"
