name: Conditions steps
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "First job"
          exit 1
      - name: print good bye
        run: |
          echo "Byee"
          echo "Multi Line Shell Commands"
  second-job:
    needs: ['first-job']
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: print greeting
        run: echo "Second job"
      - name: print good bye
        run: |
          echo "Byee"
          echo "Multi Line Shell ${{ needs.first-job.outcome }}"
