name: Filter Events
on: [ push ]
jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    outputs:
      first_var: ${{ steps.JobOutput.outputs.aa }}
    steps:
      - name: test
        run: |
          echo "test1" > aa_1.txt
          echo "test2" > aa_2.txt
      - name: store-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: '**/aa_**.txt'
      - name: JobOutput
        run: |
          aa=$(ls | tail -1)
          echo "aa=${aa}" >> $GITHUB_OUTPUT
  use-artifacts:
    needs: create_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: files
      - name: list file names
        run: echo ${{ needs.create_artifacts.outputs.first_var }}
