name: Test Workflow
on: push
jobs:
    download-code:
      runs-on: ubuntu-latest
      steps:
        - name: Clone Git Repo
          uses: actions/checkout@v4

        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install Dependencies
          run: npm ci

        - name: Run Tests
          run: npm test